microsite:
  image: vocativ/meteor
  ports:
    - "3000:3000"
  volumes:
    - ./vocativ-darknet-microsite:/app
  working_dir: /app
  env_file: ./env_files/prod.env
  command: meteor run --settings settings-dev.json

admin:
  image: vocativ/meteor
  ports:
    - "3001:3000"
  volumes:
    - ./vocativ-darknet-admin:/app
  working_dir: /app
  env_file: ./env_files/prod.env
  command: meteor run
