FROM vocativ/base-meteor
MAINTAINER nikolay

ENV \
	MONGO_URL=mongodb://darknet:darknet@candidate.57.mongolayer.com:10638,candidate.60.mongolayer.com:10516/darknet?replicaSet=set-566701aefd6b56ed9e0018e6 \
	MONGO_OPLOG_URL=mongodb://darknet:darknet@candidate.57.mongolayer.com:10638,candidate.60.mongolayer.com:10516/local?authSource=darknet \
	KADIRA_APP_ID=o5DsxrpnCK43wbpzn \
	KADIRA_APP_SECRET=8be42b29-0043-4c01-9b7e-e6108d317736

EXPOSE 8080
